# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cjmle_conf_cpp <- function(response, nonmis_ind, theta0, A0, Q, cc, tol, print_proc, parallel) {
    .Call('_mirtjml_cjmle_conf_cpp', PACKAGE = 'mirtjml', response, nonmis_ind, theta0, A0, Q, cc, tol, print_proc, parallel)
}

#' @useDynLib mirtjml
#' @importFrom Rcpp evalCpp
NULL

cjmle_expr_cpp <- function(response, nonmis_ind, theta0, A0, cc, tol, print_proc, parallel) {
    .Call('_mirtjml_cjmle_expr_cpp', PACKAGE = 'mirtjml', response, nonmis_ind, theta0, A0, cc, tol, print_proc, parallel)
}

prox_func_cpp <- function(y, C) {
    .Call('_mirtjml_prox_func_cpp', PACKAGE = 'mirtjml', y, C)
}

