# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grad_neg_loglik_A_j_conf_cpp <- function(response_j, nonmis_ind_j, A_j, Q_j, theta) {
    .Call('_mirtjml_grad_neg_loglik_A_j_conf_cpp', PACKAGE = 'mirtjml', response_j, nonmis_ind_j, A_j, Q_j, theta)
}

cjmle_conf_cpp <- function(response, nonmis_ind, theta0, A0, Q, cc, tol, print_proc) {
    .Call('_mirtjml_cjmle_conf_cpp', PACKAGE = 'mirtjml', response, nonmis_ind, theta0, A0, Q, cc, tol, print_proc)
}

#' @useDynLib mirtjml
#' @importFrom Rcpp evalCpp
NULL

#' Simulation for the book chapter
NULL

grad_neg_loglik_A_j_cpp <- function(response_j, nonmis_ind_j, A_j, theta) {
    .Call('_mirtjml_grad_neg_loglik_A_j_cpp', PACKAGE = 'mirtjml', response_j, nonmis_ind_j, A_j, theta)
}

cjmle_expr_cpp <- function(response, nonmis_ind, theta0, A0, cc, tol, print_proc) {
    .Call('_mirtjml_cjmle_expr_cpp', PACKAGE = 'mirtjml', response, nonmis_ind, theta0, A0, cc, tol, print_proc)
}

prox_func_cpp <- function(y, C) {
    .Call('_mirtjml_prox_func_cpp', PACKAGE = 'mirtjml', y, C)
}

neg_loglik <- function(thetaA, response, nonmis_ind) {
    .Call('_mirtjml_neg_loglik', PACKAGE = 'mirtjml', thetaA, response, nonmis_ind)
}

neg_loglik_i_cpp <- function(response_i, nonmis_ind_i, A, theta_i) {
    .Call('_mirtjml_neg_loglik_i_cpp', PACKAGE = 'mirtjml', response_i, nonmis_ind_i, A, theta_i)
}

grad_neg_loglik_thetai_cpp <- function(response_i, nonmis_ind_i, A, theta_i) {
    .Call('_mirtjml_grad_neg_loglik_thetai_cpp', PACKAGE = 'mirtjml', response_i, nonmis_ind_i, A, theta_i)
}

neg_loglik_j_cpp <- function(response_j, nonmis_ind_j, A_j, theta) {
    .Call('_mirtjml_neg_loglik_j_cpp', PACKAGE = 'mirtjml', response_j, nonmis_ind_j, A_j, theta)
}

getmirtjml_threads <- function() {
    .Call('_mirtjml_getmirtjml_threads', PACKAGE = 'mirtjml')
}

hasOpenMP <- function() {
    .Call('_mirtjml_hasOpenMP', PACKAGE = 'mirtjml')
}

setmirtjml_threads <- function(threads = -1L) {
    .Call('_mirtjml_setmirtjml_threads', PACKAGE = 'mirtjml', threads)
}

